kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: autoscale-hypershift
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: ${ACTION}-cronjob-${RANDOM_ID}
      namespace: ${NAMESPACE}
    spec:
      schedule: ${SCHEDULE}
      suspend: ${{DISABLED}}
      jobTemplate:
        spec:
          template:
            spec: 
              serviceAccountName: cluster-installer
              containers:
              - name: worker
                image: ${CURATOR_IMAGE}
                imagePullPolicy: IfNotPresent
                command: ['./action']
                env:
                - name: TAKE_ACTION
                  value: ${ACTION}
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              restartPolicy: OnFailure
parameters:
  - name: ACTION 
    description: Whether you want to scaledown or scale-up on the specified schedule
    value: scaledown # scaledown / scaleup
    required: true 
  - name: SCHEDULE 
    description: ScaleDown or ScaleUp schedule in UTC (e.g. "0 23 * * 0-6" is everyday at 6pm EST)
    value: 0 23 * * 0-6
    required: true 
  - name: DISABLED
    description: Disable scaledown CronJob
    value: "false"
    required: true
  - name: CURATOR_IMAGE
    description: HyperShift scaler curator image
    value: quay.io/acm-sre/autoscale-hypershift:latest
    required: true
  - name: NAMESPACE 
    description: The namespace where the scaledown CronJobs were installed
    required: true
  - name: RANDOM_ID
    generate: expression
    from: "[a-z0-9]{5}"
